### ISSUE TITLE
Update package-json-validator dependency to 0.6.x

### ISSUE THREAD

**Issue by dsebastien** [chmontgomery/gulp-nice-package#2]
Version 0.6.x has been released, which fixes an annoying issue (https://github.com/gorillamania/package.json-validator/issues/49):
https://www.npmjs.com/package/package-json-validator

This package should be updated

**Comment by dsebastien** [comment]
Great!
Could you publish a new version with this modification to npm?

**Comment by chmontgomery** [comment]
will do

**Comment by chmontgomery** [comment]
feature landed in `v1.1.0`

**Comment by dsebastien** [comment]
Thanks! :)
